apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  annotations:
    argocd.argoproj.io/hook: PreSync
type: Opaque
data:
  mongodb-root-username: ZGJhZG1pbg==
  mongodb-root-password: YWRtaW5AMTIz
