apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: {{ .Values.image.imageName }}:{{ .Values.image.imageTag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
          - containerPort: {{ .Values.image.containerPort }}
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb.secretName }}
                key: {{ .Values.mongodb.rootUserKey }}
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb.secretName }}
                key: {{ .Values.mongodb.rootUserPasswordKey }}
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.mongodb.configMapName }}
                key: {{ .Values.mongodb.configMapDbUrlKey }}
